### ISSUE TITLE
Add <x33fcon> to the upcoming list

### ISSUE THREAD

**Issue by blinkerfluid** [santosomar/virtualseccons#10]
| September 10-11, 2020 (Workshops) & September 14-15, 2020 (Conference) | x33fcon |
|------|------------|
|<September 10-11, 2020 (Workshops) & September 14-15, 2020 (Conference)> | [<x33fcon> ](<https://www.x33fcon.com>) |

**Comment by santosomar** [comment]
Thank you so much, @blinkerfluid !
