### ISSUE TITLE
Hardware.io Hardware Security Conference and Training (NL 2020)

### ISSUE THREAD

**Issue by yandreax** [santosomar/virtualseccons#3]
| Sept 27-Oct 2 | Hardware.io Netherlands 2020 | https://hardwear.io |

**Comment by santosomar** [comment]
Thank you for the contribution, @yandreax ! Hope you are doing well.

Added it via https://github.com/santosomar/virtualseccons/commit/3ec17763b1363738fd01b4c0dd13321a84e842ef
