### ISSUE TITLE
Add BSides Munich to the upcoming list

### ISSUE THREAD

**Issue by h0ng10** [santosomar/virtualseccons#6]
| Date | Event Name |
|------|------------|
| Aug 23 | Bsides Munich 2020 (https://2020.bsidesmunich.org/) |

**Comment by santosomar** [comment]
Thank you so much @h0ng10 ! Added via https://github.com/santosomar/virtualseccons/commit/f73c2542f46b737af9aee9b6d10f0a2c0a1f91fa
